<div id="headache-report">
<h3>Patient Name: {user.firstName} {user.lastName}</h3>
<h3>Report generated by iHeadache Online on {[this.enDate(new Date(),"Y-M-d ")]}</h3>
<p>Start Date: {[this.enDate(values.startDate,"Y-M-d ")]}</p>
<p>End Date: {[this.enDate(values.stopDate,"Y-M-d ")]}</p>
<p>The patient had {total_headaches} headaches between  {[this.enDate(values.startDate,"Y-M-d ")]} and  {[this.enDate(values.stopDate,"Y-M-d ")]}</p>
<h3>Please see detailed warnings and precautions at the end of this report.</h3>
<tpl for=".">
<h1 class="report">{plus.title}</h1>
<p class="report">For the {plus.chunk} between {plus.start} and {plus.end}, 
{headache_count} headaches were reported.<tpl if="no_headaches!=0"> In addition, {no_headaches} information only entries (no headache) were reported</tpl></p>
<tpl if="this.inArray('headache_types', parent.opts)">
<h2 class="report">Headaches</h2>
<tpl for="headache_types">
<p>{value} {name}</p>
</tpl>
<tpl if="headache_types.length == 0">
<p>Headaches not entered</p>
</tpl>
</tpl>
<tpl if="this.inArray('treats', parent.opts)">
<h2 class="report">Acute Treatments</h2>
<tpl for="treats">
<p>{value} {name}</p>
</tpl>
<tpl if="treats.length == 0">
<p>Acute Treatments not entered</p>
</tpl>
<br>
</tpl>
<tpl if="this.inArray('p_treats', parent.opts)">
<h2> Preventative Treatments</h2>
<tpl if="pt_start.length != 0 "> 
<p><b>Started:&nbsp</b><tpl for="pt_start">{[this.enDate(values.start,"M-d ")]}: {drugRuleDescription} {dose}<tpl if="xindex!=xcount">, </tpl></tpl>
</p>
</tpl>
<tpl if="values.pt_end.length != 0"> 
<p><b>Stopped:&nbsp</b><tpl for="pt_end">{[this.enDate(values.end,"M-d ")]}: {drugRuleDescription} {dose} ({stopReason}) <tpl if="xindex!=xcount">, </tpl></tpl>
</p>
</tpl>
<tpl if="pt_ongoing.length != 0"> 
<p><b>Current Treatments:&nbsp</b><tpl for="pt_ongoing">{drugRuleDescription} {dose} <tpl if="xindex!=xcount">, </tpl></tpl>
</tpl>
<tpl if="pt_ongoing.length == 0"> 
<p><b>Current Treatments:&nbsp</b>None</p>
</tpl>
</tpl>
<tpl if="this.inArray('midas_scores', parent.opts)">
<h2 class="report">Real-time Headache Disability Score</h2>
<p>
As of {plus.end} the real-time headache disability score is&nbsp
<tpl if="midas_scores.None==0">not estimated because less than 30 days of data is available</tpl>
<tpl if="midas_scores.None!=0">
{midas_scores.midas}<tpl if="midas_scores.Actual!=-100">  </tpl>
<tpl if="midas_scores.Estimated!=-100"> Estimated</tpl>
</tpl>
</p>
</tpl>
<tpl if="this.inArray('disability', parent.opts)">
<h2 class="report">Disability</h2>
<p>{[this.enListDisability(values.disability)]}</p>
</tpl>
<tpl if="this.inArray('triggers', parent.opts)">
<h2 class="report">Headache Triggers</h2>
<p>{[this.enList3(values.triggers)]}</p>
</tpl>
<tpl if="this.inArray('notes', parent.opts)">
<h2 class="report">Notes</h2>
<tpl if="notes.length == 0">
<p>Notes not entered</p>
</tpl>
<tpl for="notes">
<tpl if="note">
<p>{[this.enDate(values.start,"Y-M-d")]}:&nbsp {kind} &ndash; {note}</p>
</tpl>
</tpl> 
</tpl>
</tpl> 
<h3 class="disclaimer">Warnings and Precautions</h3>
<p class="disclaimer">You cannot diagnose headache type with a diary.  This is because the diagnosis requires the absence of other diseases that explain your headaches.  iHeadache uses a modification of the Internal Headache Society diagnostic rules to determine if your headache is compatible with Migraines, Probable Migraines, Tension Headaches or cannot be classified as one of these 3 headache types.  You can learn more about the International Classification of Diseases by the I.H.S. at http://www.ihs-headache.org/frame_non_members.asp . 
	Settings for the modifications of the of the headache rules is found on the preference pages.  Depending on how users use the 24 hour feature of iHeadache online, the headache days may be actual headache periods. </p>
<p></p>
<table height="100px">
</table>
</div>
